Attribute VB_Name ="modFlowChartrResKeys"
Option Explicit
'
' Resource compliment generated by Resource File Editor, version two.
' Developed by Richard H. P. Fung.
' File generated 2/6/2002 5:35:40 PM
'

'
' String Table 1
'









'
' Resources
'


' End of file
