VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IToolbar"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'December 29,2002

Public Property Get Height() As Single
End Property


Public Sub Move(Left As Single, Top As Single)

End Sub


Public Sub Show(Mode As FormShowConstants, Form As Form)

End Sub

Public Sub UpdateToForm(Item As FlowItem, Defaults As FlowChart)

End Sub


